###
# @name conversation
POST https://localhost:7210/conversations

###
POST https://localhost:7210/conversations/{{conversation.response.body.$.conversationId}}/chat
Content-Type: application/json

{
  "message": "Do you have roses in red? If so, please add a large bouquet of red roses to my cart and tell me the reference number for my order."
}

###
POST https://localhost:7210/conversations/{{conversation.response.body.$.conversationId}}/chat
Content-Type: application/json

{
  "message": "Roses are great. For which occasion do you recommend them?"
}
