###
# @name conversation
POST https://localhost:7210/conversations

###
POST https://localhost:7210/conversations/{{conversation.response.body.$.conversationId}}/chat
Content-Type: application/json

{
  "message": "Which flowers do you offer?"
}

###
POST https://localhost:7210/conversations/{{conversation.response.body.$.conversationId}}/chat
Content-Type: application/json

{
  "message": "Roses are great. For which occasion do you recommend them?"
}
